/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.norbo.projects.csaladi.kassza;

import com.norbo.projects.csaladi.kassza.adatok.BeSzamla;
import com.norbo.projects.csaladi.kassza.adatok.CegAdatokTableModel;
import com.norbo.projects.csaladi.kassza.adatok.Szamla;
import com.norbo.projects.csaladi.kassza.adatok.SzamlaHozzad;
import com.norbo.projects.csaladi.kassza.adatok.SzamlaAdatokDialog;
import com.norbo.projects.csaladi.kassza.adatok.SzamlakTableModel;
import com.norbo.projects.csaladi.kassza.adatok.table.SzinkodLabel;
import com.norbo.projects.csaladi.kassza.adatok.utils.CskFilter;
import com.norbo.projects.csaladi.kassza.adatok.utils.CsvFeldolgozo;
import com.norbo.projects.csaladi.kassza.adatok.utils.Feldolgozo;
import com.norbo.projects.csaladi.kassza.adatok.utils.GuiUtils;
import com.norbo.projects.csaladi.kassza.adatok.utils.SzamlaMelos;
import com.norbo.projects.csaladi.kassza.adatok.utils.frissito.AdatFrissitoFigyelo;
import com.norbo.projects.csaladi.kassza.adatok.utils.szamlalista.SzamlaLista;
import com.norbo.projects.csaladi.kassza.adatok.utils.szamlalista.SzamlaListaKeszito;
import com.norbo.projects.csaladi.kassza.gui.naptar.CsaladiKasszaNaptar;
import com.norbo.projects.csaladi.kassza.nyomtatas.BeSzamlaNyomat;
import com.norbo.projects.csaladi.kassza.settings.Beallitas;
import java.awt.BorderLayout;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.IconUIResource;

/**
 *
 * @author igloi
 */
public class CsaladiKasszaMain extends javax.swing.JFrame implements AdatFrissitoFigyelo, WindowListener {
    private List<Szamla> szamlaLista;
    private SzamlakTableModel tableModel;
    private Beallitas beallitas;
    
    private double egyenleg;
    
    CsaladiKasszaNaptar naptarPanel;
    
    /**
     * Creates new form CsaladiKasszaMain
     */
    public CsaladiKasszaMain() {
        initComponents();
        beallitas = new Beallitas();
        
        setIconImage(new ImageIcon(getClass().getClassLoader().getResource("resources/ikons/kassza.png")).getImage());
        
        initContent();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        beszamlaMenu = new javax.swing.JPopupMenu();
        popupTorol = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        scrollpaneBefizetett = new javax.swing.JScrollPane();
        tableSzamlak = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblOsszBefizetes = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblEgyenlegKeret = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblAktualisEgyenleg = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnAddBeSzamla = new javax.swing.JButton();
        lbVartOsszeg = new javax.swing.JLabel();
        tfBefizetesOsszeg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblHatarIdo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblVartOsszegOK = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        scrollpaneCeg = new javax.swing.JScrollPane();
        szamlaadatokTable = new javax.swing.JTable();
        naptartarolo = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menufile = new javax.swing.JMenu();
        menuBetoltes = new javax.swing.JMenuItem();
        menuMentes = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuPrint = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuReszletek = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuEgyenleg = new javax.swing.JMenuItem();

        popupTorol.setText("Töröl");
        popupTorol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupTorolActionPerformed(evt);
            }
        });
        beszamlaMenu.add(popupTorol);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Családi Kassza");
        setBackground(new java.awt.Color(0, 51, 102));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Befizetett számlák", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        tableSzamlak.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        tableSzamlak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSzamlak.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableSzamlak.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollpaneBefizetett.setViewportView(tableSzamlak);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpaneBefizetett)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpaneBefizetett, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Információ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eddig befizetett számlák összege:");

        lblOsszBefizetes.setForeground(new java.awt.Color(255, 255, 255));
        lblOsszBefizetes.setText("0 Ft");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Egyenleg keret:");

        lblEgyenlegKeret.setForeground(new java.awt.Color(255, 255, 255));
        lblEgyenlegKeret.setText("0 FT");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Aktuális egyenleg:");

        lblAktualisEgyenleg.setForeground(new java.awt.Color(255, 255, 255));
        lblAktualisEgyenleg.setText("0 FT");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAktualisEgyenleg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEgyenlegKeret, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOsszBefizetes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblOsszBefizetes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblEgyenlegKeret))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblAktualisEgyenleg))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Befizetés adatai", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        btnAddBeSzamla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ikons/kassza_ok24.png"))); // NOI18N
        btnAddBeSzamla.setText("Befizetés");
        btnAddBeSzamla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBeSzamlaActionPerformed(evt);
            }
        });

        lbVartOsszeg.setForeground(new java.awt.Color(255, 255, 255));
        lbVartOsszeg.setText("0,00 Ft");

        tfBefizetesOsszeg.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Befizeni kívánt összeg:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Várt összeg:");

        lblHatarIdo.setForeground(new java.awt.Color(255, 255, 255));
        lblHatarIdo.setText("1900-01-01");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Befizetési határidő:");

        lblVartOsszegOK.setText(" ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lbVartOsszeg, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblHatarIdo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVartOsszegOK, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBefizetesOsszeg, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddBeSzamla)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblHatarIdo))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVartOsszegOK)
                    .addComponent(jLabel3)
                    .addComponent(lbVartOsszeg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBeSzamla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBefizetesOsszeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 102, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Számlák", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        scrollpaneCeg.setMaximumSize(new java.awt.Dimension(100, 100));

        szamlaadatokTable.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        szamlaadatokTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        szamlaadatokTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        szamlaadatokTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                szamlaadatokTableMouseClicked(evt);
            }
        });
        scrollpaneCeg.setViewportView(szamlaadatokTable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollpaneCeg, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollpaneCeg, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        naptartarolo.setBackground(new java.awt.Color(0, 102, 153));
        naptartarolo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        naptartarolo.setMinimumSize(new java.awt.Dimension(0, 0));
        naptartarolo.setPreferredSize(new java.awt.Dimension(619, 200));
        naptartarolo.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(naptartarolo, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(naptartarolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menufile.setText("File");

        menuBetoltes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ikons/kassza_open.png"))); // NOI18N
        menuBetoltes.setText("Betöltés");
        menuBetoltes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBetoltesActionPerformed(evt);
            }
        });
        menufile.add(menuBetoltes);

        menuMentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ikons/kassza_save.png"))); // NOI18N
        menuMentes.setText("Mentés");
        menuMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMentesActionPerformed(evt);
            }
        });
        menufile.add(menuMentes);
        menufile.add(jSeparator2);

        menuPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ikons/kassza_print.png"))); // NOI18N
        menuPrint.setText("Nyomtatás");
        menuPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrintActionPerformed(evt);
            }
        });
        menufile.add(menuPrint);
        menufile.add(jSeparator1);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ikons/kassza_exit.png"))); // NOI18N
        jMenuItem1.setText("Kilépés");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menufile.add(jMenuItem1);

        jMenuBar1.add(menufile);

        jMenu2.setText("Szerkeszt");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ikons/kassza_edit.png"))); // NOI18N
        jMenuItem3.setText("Hozzáadás");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        menuReszletek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ikons/kassza_szamla.png"))); // NOI18N
        menuReszletek.setText("Részletek");
        menuReszletek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReszletekActionPerformed(evt);
            }
        });
        jMenu2.add(menuReszletek);
        jMenu2.add(jSeparator3);

        menuEgyenleg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ikons/kassza_money.png"))); // NOI18N
        menuEgyenleg.setText("Egyenleg");
        menuEgyenleg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEgyenlegActionPerformed(evt);
            }
        });
        jMenu2.add(menuEgyenleg);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuReszletekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReszletekActionPerformed
        SzamlaAdatokDialog.showDialog(this);
    }//GEN-LAST:event_menuReszletekActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        SzamlaHozzad szamlaHozzad = new SzamlaHozzad(this, true);
        szamlaHozzad.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnAddBeSzamlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBeSzamlaActionPerformed
        if(szamlaadatokTable.getSelectedRow() != -1) {
            Szamla szamla = szamlaLista.get(szamlaadatokTable.getSelectedRow());
            if(tfBefizetesOsszeg.getText().matches("[0-9]+")) {
                int osszeg = Integer.parseInt(tfBefizetesOsszeg.getText().trim());
                tableModel.addBeSzamla(new BeSzamla(szamla, LocalDateTime.now(), osszeg));
                
                lblOsszBefizetes.setText(String.format("%,.2f Ft", tableModel.getSzamlakOsszege()));
                
                initEgyneleg();
                initVartOsszegIkon();
            } else {
                JOptionPane.showMessageDialog(this, "Csak számot fogadok el!", "Számla",
                    JOptionPane.ERROR_MESSAGE);
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Nincs kiválasztva hogy kinek megy az összeg", "Számla",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddBeSzamlaActionPerformed

    private void menuMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMentesActionPerformed
        if(!tableModel.getSzamlak().isEmpty()) {
            String opt = JOptionPane.showInputDialog("Kérem a fájl nevét");
            if(opt != null) {
                File f = new File(System.getProperty("user.home")+File.separator+opt+".csk");
                Feldolgozo<File, List<BeSzamla>> feldolgozo = new Feldolgozo<>(new CsvFeldolgozo());
                if(feldolgozo.ment(f, tableModel.getSzamlak())) {
                    JOptionPane.showMessageDialog(this, "Sikeres mentés!", "Mentés",
                        JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Sikertelen mentés", "Mentés",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nincs mit elmenteni", "Mentés",
                        JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuMentesActionPerformed

    private void menuBetoltesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBetoltesActionPerformed
        JFileChooser jfc = new JFileChooser(System.getProperty("user.home"));
        jfc.setFileFilter(new CskFilter());
        if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            Feldolgozo<File, List<BeSzamla>> feldolgozo = new Feldolgozo<>(new CsvFeldolgozo());
            List<BeSzamla> szamla = feldolgozo.betolt(jfc.getSelectedFile());
            if(szamla != null) {
                tableModel.setSzamlak(szamla);
                lblOsszBefizetes.setText(String.format("%,.2f Ft", tableModel.getSzamlakOsszege()));
                initEgyneleg();
            }
        }
    }//GEN-LAST:event_menuBetoltesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int ok = JOptionPane.showConfirmDialog(this, "Biztosan kiakarsz lépni!", "Kilépés",
                JOptionPane.OK_CANCEL_OPTION);
        if(ok == JOptionPane.OK_OPTION) {
            beallitas.saveBeallitas();
            setVisible(false);
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrintActionPerformed
        List<BeSzamla> pszamlak = tableModel.getSzamlak();
        if(!pszamlak.isEmpty()) {
            PrinterJob job = PrinterJob.getPrinterJob();
            job.setPrintable(new BeSzamlaNyomat(pszamlak));
            boolean okey = job.printDialog();
            if(okey) {
                try {
                    job.print();
                } catch (PrinterException e) {
                    System.out.println("Nem tudtam nyomtatni! "+e);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Üres listát nem lehet nyomtatni", "Nyomtatás",
                        JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_menuPrintActionPerformed

    private void szamlaadatokTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_szamlaadatokTableMouseClicked
        if(evt.getClickCount() == 1) {
            if(szamlaadatokTable.getSelectedRow() != -1) {
                Szamla sz = szamlaLista.get(szamlaadatokTable.getSelectedRow());
                lbVartOsszeg.setText(String.format("%,.2f Ft", sz.getOsszeg()));
                lblHatarIdo.setText(sz.getBefizetesHatarido().toString());
                btnAddBeSzamla.setBackground(GuiUtils.parseColor(sz.getKijeloles()));
                naptarPanel.setHataridoKijeloltSzamla(sz);
                initVartOsszegIkon();
            }
        }
    }//GEN-LAST:event_szamlaadatokTableMouseClicked

    private void popupTorolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupTorolActionPerformed
        if(tableSzamlak.getSelectedRow() != -1) {
            tableModel.removeItem(tableSzamlak.getSelectedRow());
            
            lblOsszBefizetes.setText(String.format("%,.2f Ft", tableModel.getSzamlakOsszege()));
            initEgyneleg();
            initVartOsszegIkon();
        } else {
            JOptionPane.showMessageDialog(this, "Törléshez válasszd ki a törölni kívánt sort.", "Törlés",
                        JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_popupTorolActionPerformed

    private void menuEgyenlegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEgyenlegActionPerformed
        String ertek = JOptionPane.showInputDialog("Kérem a felhasználható egyenleget");
        if(ertek != null && ertek.matches("[0-9]+")) {
            beallitas.setProp(Beallitas.EGYENLEG, ertek);
            egyenleg = Double.parseDouble(ertek);
            
            initEgyneleg();
        } else {
            JOptionPane.showMessageDialog(this, "Nem adtál meg értéket, vagy nem számokat írtál be!","Egyenleg",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_menuEgyenlegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CsaladiKasszaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CsaladiKasszaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CsaladiKasszaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CsaladiKasszaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CsaladiKasszaMain().setVisible(true);
            }
        });
    }
    
    private void initContent() {
//        initSzamlaComboBox();
        naptarPanel = new CsaladiKasszaNaptar(this);
        naptarPanel.setSize(400,300);
        naptartarolo.add(naptarPanel, BorderLayout.CENTER);
        
        szamlaLista = SzamlaMelos.getSzamlakFromDB();
        naptarPanel.setSzamlak(szamlaLista);
        
        tableModel = new SzamlakTableModel();
        tableSzamlak.setModel(tableModel);
        tableSzamlak.setComponentPopupMenu(beszamlaMenu);
        
        //cég számlák listájának iniciílizálása
        szamlaadatokTable.setModel(new CegAdatokTableModel(szamlaLista));
        szamlaadatokTable.setDefaultRenderer(SzinkodLabel.class, new SzinkodLabel());
        GuiUtils.coloriseTable(scrollpaneCeg, GuiUtils.DEFTABLEBGCOLOR, null);
        GuiUtils.coloriseTable(scrollpaneBefizetett, GuiUtils.DEFTABLEBGCOLOR, null);
        GuiUtils.coloriseTablaHeader(new JTable[]{tableSzamlak,szamlaadatokTable}, 
                GuiUtils.THBGCOLOR, 
                GuiUtils.THFGCOLOR);
        
        initEgyneleg();
        addWindowListener(this);
        
        initBeSzamlaMentesekToNaptar();
    }

    private void initBeSzamlaMentesekToNaptar() {
        //mentett számlalista betöltésének tesztelése
        SzamlaListaKeszito<File, List<BeSzamla>> makelist = new SzamlaListaKeszito<>(
                System.getProperty("user.home"), new CsvFeldolgozo());
        List<SzamlaLista> lista = makelist.getSzamlaListas();
        for (SzamlaLista szl : lista) {
            naptarPanel.setNapMentese(szl);
        }
    }

    private void initEgyneleg() throws NumberFormatException {
        //a fentieket is a beállítás fájlban fogom majd eltárolni, szinek stb..
        egyenleg = Double.parseDouble(beallitas.getProp(Beallitas.EGYENLEG));
        lblEgyenlegKeret.setText(String.format("%,.2f (Ft)", egyenleg));
        //aktiálisan kell majd frissítenem az elérhető egyenleget (minuszba nem kellene lemenni)
        lblAktualisEgyenleg.setText(String.format("%,.2f (Ft)", (egyenleg - tableModel.getSzamlakOsszege())));
        
        //initVartOsszegIkon();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu beszamlaMenu;
    private javax.swing.JButton btnAddBeSzamla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lbVartOsszeg;
    private javax.swing.JLabel lblAktualisEgyenleg;
    private javax.swing.JLabel lblEgyenlegKeret;
    private javax.swing.JLabel lblHatarIdo;
    private javax.swing.JLabel lblOsszBefizetes;
    private javax.swing.JLabel lblVartOsszegOK;
    private javax.swing.JMenuItem menuBetoltes;
    private javax.swing.JMenuItem menuEgyenleg;
    private javax.swing.JMenuItem menuMentes;
    private javax.swing.JMenuItem menuPrint;
    private javax.swing.JMenuItem menuReszletek;
    private javax.swing.JMenu menufile;
    private javax.swing.JPanel naptartarolo;
    private javax.swing.JMenuItem popupTorol;
    private javax.swing.JScrollPane scrollpaneBefizetett;
    private javax.swing.JScrollPane scrollpaneCeg;
    private javax.swing.JTable szamlaadatokTable;
    private javax.swing.JTable tableSzamlak;
    private javax.swing.JTextField tfBefizetesOsszeg;
    // End of variables declaration//GEN-END:variables

    @Override
    public void adatFrissites(String classname) {
        szamlaLista = SzamlaMelos.getSzamlakFromDB();
        naptarPanel.setSzamlak(szamlaLista);
        ((CegAdatokTableModel)szamlaadatokTable.getModel()).setSzamlak(szamlaLista);
    }

    @Override
    public void windowOpened(WindowEvent e) {
        
    }

    @Override
    public void windowClosing(WindowEvent e) {
         beallitas.saveBeallitas();
    }

    @Override
    public void windowClosed(WindowEvent e) {
        
    }

    @Override
    public void windowIconified(WindowEvent e) {
        
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        
    }

    @Override
    public void windowActivated(WindowEvent e) {
        
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        
    }

    private void initVartOsszegIkon() {
        if(szamlaadatokTable.getSelectedRow() != -1) {
            Szamla sz = szamlaLista.get(szamlaadatokTable.getSelectedRow());
            List<BeSzamla> besz = tableModel.getSzamlak();
            
            double osszeg = 0.0;
            for (BeSzamla be : besz) {
                if(be.getSzamla().equals(sz)) {
                    osszeg += be.getOsszeg();
                }
            }
            
            if (sz.getOsszeg() <= osszeg) {
                lblVartOsszegOK.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/ikons/kassza_love_ok.png")));
            } else {
                lblVartOsszegOK.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/ikons/kassza_love_not.png")));
            }
        }
    }

    @Override
    public void initMentettSzamlak() {
        initBeSzamlaMentesekToNaptar();
    }
    
    
}
