/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.norbo.projects.csaladi.kassza;

import com.norbo.projects.csaladi.kassza.adatok.BeSzamla;
import com.norbo.projects.csaladi.kassza.adatok.CegAdatokTableModel;
import com.norbo.projects.csaladi.kassza.adatok.Szamla;
import com.norbo.projects.csaladi.kassza.adatok.SzamlaHozzad;
import com.norbo.projects.csaladi.kassza.adatok.SzamlaAdatokDialog;
import com.norbo.projects.csaladi.kassza.adatok.SzamlakTableModel;
import com.norbo.projects.csaladi.kassza.adatok.table.SzinkodLabel;
import com.norbo.projects.csaladi.kassza.adatok.utils.CskFilter;
import com.norbo.projects.csaladi.kassza.adatok.utils.CsvFeldolgozo;
import com.norbo.projects.csaladi.kassza.adatok.utils.Feldolgozo;
import com.norbo.projects.csaladi.kassza.adatok.utils.GuiUtils;
import com.norbo.projects.csaladi.kassza.adatok.utils.SzamlaMelos;
import com.norbo.projects.csaladi.kassza.adatok.utils.frissito.AdatFrissitoFigyelo;
import com.norbo.projects.csaladi.kassza.gui.naptar.CsaladiKasszaNaptar;
import com.norbo.projects.csaladi.kassza.nyomtatas.BeSzamlaNyomat;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author igloi
 */
public class CsaladiKasszaMain extends javax.swing.JFrame implements AdatFrissitoFigyelo{
    private static final String VALASSZ = " -- Válassz -- ";
    private List<Szamla> szamlaLista;
    private DefaultComboBoxModel<String> cbmodel;
    private SzamlakTableModel tableModel;
    private CsaladiKasszaNaptar naptar;

    /**
     * Creates new form CsaladiKasszaMain
     */
    public CsaladiKasszaMain() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getClassLoader().getResource("resources/ikons/kassza.png")).getImage());
        
        initContent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        beszamlaMenu = new javax.swing.JPopupMenu();
        popupTorol = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSzamlak = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblOsszBefizetes = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnAddBeSzamla = new javax.swing.JButton();
        lbVartOsszeg = new javax.swing.JLabel();
        tfBefizetesOsszeg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblHatarIdo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSzinkod = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        szamlaadatokTable = new javax.swing.JTable();
        naptarPanel = new com.norbo.projects.csaladi.kassza.gui.naptar.CsaladiKasszaNaptar();
        jMenuBar1 = new javax.swing.JMenuBar();
        menufile = new javax.swing.JMenu();
        menuBetoltes = new javax.swing.JMenuItem();
        menuMentes = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuPrint = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuReszletek = new javax.swing.JMenuItem();

        popupTorol.setText("Töröl");
        popupTorol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupTorolActionPerformed(evt);
            }
        });
        beszamlaMenu.add(popupTorol);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Családi Kassza");
        setBackground(new java.awt.Color(0, 51, 102));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Befizetett számlák", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        tableSzamlak.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        tableSzamlak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSzamlak.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableSzamlak.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableSzamlak);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Információ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eddig befizetett számlák összege:");

        lblOsszBefizetes.setForeground(new java.awt.Color(255, 255, 255));
        lblOsszBefizetes.setText("0 Ft");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOsszBefizetes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblOsszBefizetes))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Befizetés adatai", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        btnAddBeSzamla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ikons/kassza_ok.png"))); // NOI18N
        btnAddBeSzamla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBeSzamlaActionPerformed(evt);
            }
        });

        lbVartOsszeg.setForeground(new java.awt.Color(255, 255, 255));
        lbVartOsszeg.setText("0,00 Ft");

        tfBefizetesOsszeg.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Befizeni kívánt összeg:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Várt összeg:");

        lblHatarIdo.setForeground(new java.awt.Color(255, 255, 255));
        lblHatarIdo.setText("1900-01-01");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Befizetési határidő:");

        lblSzinkod.setBackground(new java.awt.Color(0, 102, 153));
        lblSzinkod.setForeground(new java.awt.Color(0, 0, 0));
        lblSzinkod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSzinkod.setText("Színkód:");
        lblSzinkod.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBefizetesOsszeg, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHatarIdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbVartOsszeg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddBeSzamla, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSzinkod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddBeSzamla, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSzinkod, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfBefizetesOsszeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblHatarIdo))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbVartOsszeg))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 102, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Számlák", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jScrollPane2.setMaximumSize(new java.awt.Dimension(100, 100));

        szamlaadatokTable.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        szamlaadatokTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        szamlaadatokTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                szamlaadatokTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(szamlaadatokTable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        naptarPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(naptarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(naptarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menufile.setText("File");

        menuBetoltes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ikons/kassza_open.png"))); // NOI18N
        menuBetoltes.setText("Betöltés");
        menuBetoltes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBetoltesActionPerformed(evt);
            }
        });
        menufile.add(menuBetoltes);

        menuMentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ikons/kassza_save.png"))); // NOI18N
        menuMentes.setText("Mentés");
        menuMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMentesActionPerformed(evt);
            }
        });
        menufile.add(menuMentes);
        menufile.add(jSeparator2);

        menuPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ikons/kassza_print.png"))); // NOI18N
        menuPrint.setText("Nyomtatás");
        menuPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrintActionPerformed(evt);
            }
        });
        menufile.add(menuPrint);
        menufile.add(jSeparator1);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ikons/kassza_exit.png"))); // NOI18N
        jMenuItem1.setText("Kilépés");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menufile.add(jMenuItem1);

        jMenuBar1.add(menufile);

        jMenu2.setText("Szerkeszt");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ikons/kassza_edit.png"))); // NOI18N
        jMenuItem3.setText("Hozzáadás");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        menuReszletek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ikons/kassza_szamla.png"))); // NOI18N
        menuReszletek.setText("Részletek");
        menuReszletek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReszletekActionPerformed(evt);
            }
        });
        jMenu2.add(menuReszletek);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuReszletekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReszletekActionPerformed
        SzamlaAdatokDialog.showDialog(this);
    }//GEN-LAST:event_menuReszletekActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        SzamlaHozzad szamlaHozzad = new SzamlaHozzad(this, true);
        szamlaHozzad.setVisible(true);
        
//        Ezt kiveszem, mivel adatbázisból dolgozok, igy onnan frissitem a számlákat és egyébb tartalmat
//        Szamla sz = szamlaHozzad.getSzamla();
//        if (sz != null) {
//            JOptionPane.showMessageDialog(this, "Számla hozzáadása megtörtént: " + sz.getMegjelenoNev(), "Számla",
//                    JOptionPane.INFORMATION_MESSAGE);
//            szamlaLista.add(sz);
//            cbmodel.addElement(sz.getMegjelenoNev());
//        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnAddBeSzamlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBeSzamlaActionPerformed
        if(szamlaadatokTable.getSelectedRow() != -1) {
            Szamla szamla = szamlaLista.get(szamlaadatokTable.getSelectedRow());
            if(tfBefizetesOsszeg.getText().matches("[0-9]+")) {
                int osszeg = Integer.parseInt(tfBefizetesOsszeg.getText().trim());
                tableModel.addBeSzamla(new BeSzamla(szamla, LocalDateTime.now(), osszeg));
                
                lblOsszBefizetes.setText(String.format("%,.2f", tableModel.getSzamlakOsszege()));
            } else {
                JOptionPane.showMessageDialog(this, "Csak számot fogadok el!", "Számla",
                    JOptionPane.ERROR_MESSAGE);
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Nincs kiválasztva hogy kinek megy az összeg", "Számla",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddBeSzamlaActionPerformed

    private void menuMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMentesActionPerformed
        if(!tableModel.getSzamlak().isEmpty()) {
            String opt = JOptionPane.showInputDialog("Kérem a fájl nevét");
            if(opt != null) {
                File f = new File(System.getProperty("user.home")+File.separator+opt+".csk");
                Feldolgozo<File, List<BeSzamla>> feldolgozo = new Feldolgozo<>(new CsvFeldolgozo());
                if(feldolgozo.ment(f, tableModel.getSzamlak())) {
                    JOptionPane.showMessageDialog(this, "Sikeres mentés!", "Mentés",
                        JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Sikertelen mentés", "Mentés",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nincs mit elmenteni", "Mentés",
                        JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuMentesActionPerformed

    private void menuBetoltesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBetoltesActionPerformed
        JFileChooser jfc = new JFileChooser(System.getProperty("user.home"));
        jfc.setFileFilter(new CskFilter());
        if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            Feldolgozo<File, List<BeSzamla>> feldolgozo = new Feldolgozo<>(new CsvFeldolgozo());
            List<BeSzamla> szamla = feldolgozo.betolt(jfc.getSelectedFile());
            if(szamla != null) {
                tableModel.setSzamlak(szamla);
            }
        }
    }//GEN-LAST:event_menuBetoltesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int ok = JOptionPane.showConfirmDialog(this, "Biztosan kiakarsz lépni!", "Kilépés",
                JOptionPane.OK_CANCEL_OPTION);
        if(ok == JOptionPane.OK_OPTION) {
            setVisible(false);
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrintActionPerformed
        List<BeSzamla> pszamlak = tableModel.getSzamlak();
        if(!pszamlak.isEmpty()) {
            PrinterJob job = PrinterJob.getPrinterJob();
            job.setPrintable(new BeSzamlaNyomat(pszamlak));
            boolean okey = job.printDialog();
            if(okey) {
                try {
                    job.print();
                } catch (PrinterException e) {
                    System.out.println("Nem tudtam nyomtatni! "+e);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Üres listát nem lehet nyomtatni", "Nyomtatás",
                        JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_menuPrintActionPerformed

    private void szamlaadatokTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_szamlaadatokTableMouseClicked
        if(evt.getClickCount() == 2) {
            if(szamlaadatokTable.getSelectedRow() != -1) {
                Szamla sz = szamlaLista.get(szamlaadatokTable.getSelectedRow());
                lbVartOsszeg.setText(String.format("%,.2f Ft", sz.getOsszeg()));
                lblHatarIdo.setText(sz.getBefizetesHatarido().toString());
                lblSzinkod.setBackground(GuiUtils.parseColor(sz.getKijeloles()));
                naptarPanel.setHataridoKijeloltSzamla(sz);
            }
        }
    }//GEN-LAST:event_szamlaadatokTableMouseClicked

    private void popupTorolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupTorolActionPerformed
        if(tableSzamlak.getSelectedRow() != -1) {
            tableModel.removeItem(tableSzamlak.getSelectedRow());
            
            lblOsszBefizetes.setText(String.format("%,.2f Ft", tableModel.getSzamlakOsszege()));
        } else {
            JOptionPane.showMessageDialog(this, "Törléshez válasszd ki a törölni kívánt sort.", "Törlés",
                        JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_popupTorolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CsaladiKasszaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CsaladiKasszaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CsaladiKasszaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CsaladiKasszaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CsaladiKasszaMain().setVisible(true);
            }
        });
    }
    
    private void initContent() {
//        initSzamlaComboBox();
        szamlaLista = SzamlaMelos.getSzamlakFromDB();
        naptarPanel.setSzamlak(szamlaLista);
        
        tableModel = new SzamlakTableModel();
        tableSzamlak.setModel(tableModel);
        tableSzamlak.setComponentPopupMenu(beszamlaMenu);
        
        //cég számlák listájának iniciílizálása
        szamlaadatokTable.setModel(new CegAdatokTableModel(szamlaLista));
        szamlaadatokTable.setDefaultRenderer(SzinkodLabel.class, new SzinkodLabel());
        
    }
    
    private void initTabla() {
        
    }

//    private void initSzamlaComboBox() {
//        cbSzamlaLista.removeAllItems();
//        
//        szamlaLista = SzamlaMelos.getSzamlakFromDB();
//        naptarPanel.setSzamlak(szamlaLista);
//        
//        cbmodel = new DefaultComboBoxModel<>();
//        cbSzamlaLista.setModel(cbmodel);
//        
//        cbmodel.addElement(VALASSZ);
//        szamlaLista.forEach(o -> cbmodel.addElement(o.getMegjelenoNev()));
//        
//        cbSzamlaLista.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent arg0) {
//                if(cbSzamlaLista.getSelectedIndex() != -1) {
//                    if(!cbSzamlaLista.getSelectedItem().toString().equals(VALASSZ)) {
//                        Szamla szamla = szamlaLista.get(cbSzamlaLista.getSelectedIndex() - 1);
//                        lbVartOsszeg.setText(String.format("%,.2f Ft", szamla.getOsszeg()));
//                        lblHatarIdo.setText(szamla.getBefizetesHatarido().toString());
//                        lblSzinkod.setBackground(GuiUtils.parseColor(szamla.getKijeloles()));
//                        naptarPanel.setHataridoKijeloltSzamla(szamla);
//                    } else {
//                        lbVartOsszeg.setText(String.format("%,.2f Ft", 0.0));
//                        lblHatarIdo.setText("1900-01-01");
//                        lblSzinkod.setBackground(getBackground());
//                        naptarPanel.clearHataridoKijeloltSzamlak();
//                    }
//                }
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu beszamlaMenu;
    private javax.swing.JButton btnAddBeSzamla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lbVartOsszeg;
    private javax.swing.JLabel lblHatarIdo;
    private javax.swing.JLabel lblOsszBefizetes;
    private javax.swing.JLabel lblSzinkod;
    private javax.swing.JMenuItem menuBetoltes;
    private javax.swing.JMenuItem menuMentes;
    private javax.swing.JMenuItem menuPrint;
    private javax.swing.JMenuItem menuReszletek;
    private javax.swing.JMenu menufile;
    private com.norbo.projects.csaladi.kassza.gui.naptar.CsaladiKasszaNaptar naptarPanel;
    private javax.swing.JMenuItem popupTorol;
    private javax.swing.JTable szamlaadatokTable;
    private javax.swing.JTable tableSzamlak;
    private javax.swing.JTextField tfBefizetesOsszeg;
    // End of variables declaration//GEN-END:variables

    @Override
    public void adatFrissites(String classname) {
        szamlaLista = SzamlaMelos.getSzamlakFromDB();
        ((CegAdatokTableModel)szamlaadatokTable.getModel()).setSzamlak(szamlaLista);
//        initSzamlaComboBox();
    }

}
