/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.norbo.projects.csaladi.kassza.gui.naptar;

import java.awt.Component;
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author igloi
 */
public class CsaladiKasszaNaptar extends javax.swing.JPanel {

    private LocalDate datum = LocalDate.now();
    private List<JButton> buttons = new ArrayList<>();
    
    /**
     * Creates new form CsaladiKasszaNaptar
     */
    public CsaladiKasszaNaptar() {
        initComponents();
        
        initMe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        napokPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblHonapNeve = new javax.swing.JLabel();
        btnPrevMonth = new javax.swing.JButton();
        btnNextMonth = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 153));

        napokPanel.setBackground(new java.awt.Color(0, 153, 204));
        napokPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        napokPanel.setLayout(new java.awt.GridLayout(0, 7, 5, 5));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("H");
        napokPanel.add(jLabel1);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("K");
        napokPanel.add(jLabel2);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sze");
        napokPanel.add(jLabel3);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cs");
        napokPanel.add(jLabel4);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("P");
        napokPanel.add(jLabel5);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Szo");
        napokPanel.add(jLabel6);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("V");
        napokPanel.add(jLabel7);

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        lblHonapNeve.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblHonapNeve.setForeground(new java.awt.Color(0, 0, 0));
        lblHonapNeve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHonapNeve.setText("Hónap neve");

        btnPrevMonth.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPrevMonth.setText("<");
        btnPrevMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevMonthActionPerformed(evt);
            }
        });

        btnNextMonth.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnNextMonth.setText(">");
        btnNextMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextMonthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(btnPrevMonth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHonapNeve, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNextMonth)
                .addGap(80, 80, 80))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblHonapNeve)
                .addComponent(btnPrevMonth)
                .addComponent(btnNextMonth))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(napokPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(napokPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextMonthActionPerformed
        removeAllButtons();
        datum = datum.plusMonths(1);
        initMe();
        revalidate();
    }//GEN-LAST:event_btnNextMonthActionPerformed

    private void btnPrevMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevMonthActionPerformed
        removeAllButtons();
        datum = datum.minusMonths(1);
        initMe();
        revalidate();
    }//GEN-LAST:event_btnPrevMonthActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNextMonth;
    private javax.swing.JButton btnPrevMonth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblHonapNeve;
    private javax.swing.JPanel napokPanel;
    // End of variables declaration//GEN-END:variables

    private void initMe() {
        lblHonapNeve.setText(datum.getMonth().name());
        int napokszama = datum.lengthOfMonth();
        
        for (int i = 1; i <= napokszama; i++) {
            buttons.add(new JButton(""+i));
        }
        
        LocalDate honap = LocalDate.of(datum.getYear(), datum.getMonth(), 1);
        int elsoNapHetNapja = honap.getDayOfWeek().getValue();
        
        //panel feltöltése a gombokkal
        for (int i = 1; i < elsoNapHetNapja; i++) {
            JButton b = new JButton();
            b.setEnabled(false);
            napokPanel.add(b);
        }
        
        for(int i=0; i<buttons.size(); i++) {
            napokPanel.add(buttons.get(i));
        }   
    }
    
    private void removeAllButtons() {
        for(Component c: napokPanel.getComponents()) {
            if(c instanceof JButton) {
                napokPanel.remove(c);
            }
        }
        
        buttons.clear();
    }
}
